package ca.ubc.ece.resess.taint.dynamic.vialin;

import java.util.List;


public class Reflection {
    public static int injectTaintSeedIfReflectiveSource(TaintTool tool, String methodRegister, String paramRegister, String targetReg, String signatureRegister, int lineNumber, List<String> linesToAdd, List<String> extraTaintMethods, int taintTempReg, String className, int maxRegs) {

        linesToAdd.add("    move-object/16 v" + taintTempReg + ", " + methodRegister);
        linesToAdd.add("    " + tool.getMoveTaint() + "/16 v" + String.valueOf(taintTempReg+1) + ", " + paramRegister);
        linesToAdd.add("    move-object/16 v" + String.valueOf(taintTempReg+2) + ", " + signatureRegister);
        linesToAdd.add("    move-object/16 v" + String.valueOf(taintTempReg+3) + ", " + targetReg);
        String methodSig;
        if (tool instanceof ViaLinTool) {
            methodSig = "injectTaintSeedIfReflectiveSource"+lineNumber+"(Ljava/lang/reflect/Method;Ljava/lang/PathTaint;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/PathTaint;";
        } else {
            methodSig = "injectTaintSeedIfReflectiveSource"+lineNumber+"(Ljava/lang/reflect/Method;ILjava/lang/Thread;Ljava/lang/Object;)I";
        }
        linesToAdd.add("    invoke-static/range {v" + taintTempReg + " .. v" + String.valueOf(taintTempReg+3) + "}, " + className + "->" + methodSig);

        // System.out.println("    Added call to injectTaintSeedIfReflectiveSource");
        String methodCall = ".method public static " + methodSig;
        if (!extraTaintMethods.contains(methodCall)) {
            extraTaintMethods.add(methodCall);
            extraTaintMethods.add("    .registers 40");

            extraTaintMethods.add("    new-instance v0, Ljava/util/ArrayList;");
            extraTaintMethods.add("    invoke-direct {v0}, Ljava/util/ArrayList;-><init>()V");

            for (String source : TaintSource.getSources()) {
                extraTaintMethods.add("    const-string v1, \"" + source + "\"");
                extraTaintMethods.add("    invoke-interface {v0, v1}, Ljava/util/List;->add(Ljava/lang/Object;)Z");
            }

            extraTaintMethods.add("    invoke-virtual/range {p0 .. p0}, Ljava/lang/reflect/Method;->getDeclaringClass()Ljava/lang/Class;");
            extraTaintMethods.add("    move-result-object v1");
            extraTaintMethods.add("    invoke-virtual {v1}, Ljava/lang/Class;->getName()Ljava/lang/String;");
            extraTaintMethods.add("    move-result-object v1");
            extraTaintMethods.add("    new-instance v2, Ljava/lang/StringBuilder;");
            extraTaintMethods.add("    invoke-direct {v2}, Ljava/lang/StringBuilder;-><init>()V");
            extraTaintMethods.add("    const-string v3, \"L\"");
            extraTaintMethods.add("    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;");
            extraTaintMethods.add("    const-string v4, \".\"");
            extraTaintMethods.add("    const-string v5, \"/\"");
            extraTaintMethods.add("    invoke-virtual {v1, v4, v5}, Ljava/lang/String;->replace(Ljava/lang/CharSequence;Ljava/lang/CharSequence;)Ljava/lang/String;");
            extraTaintMethods.add("    move-result-object v1");
            extraTaintMethods.add("    invoke-virtual {v2, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;");
            extraTaintMethods.add("    const-string v1, \";->\"");
            extraTaintMethods.add("    invoke-virtual {v2, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;");
            extraTaintMethods.add("    invoke-virtual/range {p0 .. p0}, Ljava/lang/reflect/Method;->getName()Ljava/lang/String;");
            extraTaintMethods.add("    move-result-object v1");
            extraTaintMethods.add("    invoke-virtual {v2, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;");
            extraTaintMethods.add("    const-string v1, \"(\"");
            extraTaintMethods.add("    invoke-virtual {v2, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;");
            extraTaintMethods.add("    invoke-virtual/range {p0 .. p0}, Ljava/lang/reflect/Method;->getParameterTypes()[Ljava/lang/Class;");
            extraTaintMethods.add("    move-result-object v1");
            extraTaintMethods.add("    array-length v6, v1");
            extraTaintMethods.add("    const/4 v7, 0x0");
            extraTaintMethods.add("    const v30, 0x0");
            extraTaintMethods.add("    :goto_0");
            extraTaintMethods.add("    const-string v8, \"S\"");
            extraTaintMethods.add("    const-string v9, \";\"");
            extraTaintMethods.add("    const-string v10, \"J\"");
            extraTaintMethods.add("    const-string v11, \"short\"");
            extraTaintMethods.add("    const-string v12, \"I\"");
            extraTaintMethods.add("    const-string v13, \"long\"");
            extraTaintMethods.add("    const-string v14, \"F\"");
            extraTaintMethods.add("    const-string v15, \"int\"");
            extraTaintMethods.add("    move-object/from16 v16, v0");
            extraTaintMethods.add("    const-string v0, \"D\"");
            extraTaintMethods.add("    move-object/from16 v17, v9");
            extraTaintMethods.add("    const-string v9, \"float\"");
            extraTaintMethods.add("    move-object/from16 v18, v4");
            extraTaintMethods.add("    const-string v4, \"C\"");
            extraTaintMethods.add("    move-object/from16 v19, v5");
            extraTaintMethods.add("    const-string v5, \"double\"");
            extraTaintMethods.add("    move-object/from16 v20, v3");
            extraTaintMethods.add("    const-string v3, \"B\"");
            extraTaintMethods.add("    move-object/from16 v21, v8");
            extraTaintMethods.add("    const-string v8, \"char\"");
            extraTaintMethods.add("    move-object/from16 v22, v11");
            extraTaintMethods.add("    const-string v11, \"Z\"");
            extraTaintMethods.add("    move-object/from16 v23, v10");
            extraTaintMethods.add("    const-string v10, \"byte\"");
            extraTaintMethods.add("    move-object/from16 v24, v13");
            extraTaintMethods.add("    const-string v13, \"boolean\"");
            extraTaintMethods.add("    if-ge v7, v6, :cond_8");
            extraTaintMethods.add("    aget-object v25, v1, v7");
            extraTaintMethods.add("    move-object/from16 v26, v1");
            extraTaintMethods.add("    invoke-virtual/range {v25 .. v25}, Ljava/lang/Class;->getName()Ljava/lang/String;");
            extraTaintMethods.add("    move-result-object v1");
            extraTaintMethods.add("    invoke-virtual {v1, v13}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z");
            extraTaintMethods.add("    move-result v13");
            extraTaintMethods.add("    if-eqz v13, :cond_0");
            extraTaintMethods.add("    invoke-virtual {v2, v11}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;");
            extraTaintMethods.add("    :goto_1");
            extraTaintMethods.add("    move-object/from16 v4, v18");
            extraTaintMethods.add("    move-object/from16 v3, v19");
            extraTaintMethods.add("    move-object/from16 v0, v20");
            extraTaintMethods.add("    goto/16 :goto_2");
            extraTaintMethods.add("    :cond_0");
            extraTaintMethods.add("    invoke-virtual {v1, v10}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z");
            extraTaintMethods.add("    move-result v10");
            extraTaintMethods.add("    if-eqz v10, :cond_1");
            extraTaintMethods.add("    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;");
            extraTaintMethods.add("    goto :goto_1");
            extraTaintMethods.add("    :cond_1");
            extraTaintMethods.add("    invoke-virtual {v1, v8}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z");
            extraTaintMethods.add("    move-result v3");
            extraTaintMethods.add("    if-eqz v3, :cond_2");
            extraTaintMethods.add("    invoke-virtual {v2, v4}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;");
            extraTaintMethods.add("    goto :goto_1");
            extraTaintMethods.add("    :cond_2");
            extraTaintMethods.add("    invoke-virtual {v1, v5}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z");
            extraTaintMethods.add("    move-result v3");
            extraTaintMethods.add("    if-eqz v3, :cond_3");
            extraTaintMethods.add("    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;");
            extraTaintMethods.add("    goto :goto_1");
            extraTaintMethods.add("    :cond_3");
            extraTaintMethods.add("    invoke-virtual {v1, v9}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z");
            extraTaintMethods.add("    move-result v0");
            extraTaintMethods.add("    if-eqz v0, :cond_4");
            extraTaintMethods.add("    invoke-virtual {v2, v14}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;");
            extraTaintMethods.add("    goto :goto_1");
            extraTaintMethods.add("    :cond_4");
            extraTaintMethods.add("    invoke-virtual {v1, v15}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z");
            extraTaintMethods.add("    move-result v0");
            extraTaintMethods.add("    if-eqz v0, :cond_5");
            extraTaintMethods.add("    invoke-virtual {v2, v12}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;");
            extraTaintMethods.add("    goto :goto_1");
            extraTaintMethods.add("    :cond_5");
            extraTaintMethods.add("    move-object/from16 v0, v24");
            extraTaintMethods.add("    invoke-virtual {v1, v0}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z");
            extraTaintMethods.add("    move-result v0");
            extraTaintMethods.add("    if-eqz v0, :cond_6");
            extraTaintMethods.add("    move-object/from16 v0, v23");
            extraTaintMethods.add("    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;");
            extraTaintMethods.add("    goto :goto_1");
            extraTaintMethods.add("    :cond_6");
            extraTaintMethods.add("    move-object/from16 v0, v22");
            extraTaintMethods.add("    invoke-virtual {v1, v0}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z");
            extraTaintMethods.add("    move-result v0");
            extraTaintMethods.add("    if-eqz v0, :cond_7");
            extraTaintMethods.add("    move-object/from16 v0, v21");
            extraTaintMethods.add("    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;");
            extraTaintMethods.add("    goto :goto_1");
            extraTaintMethods.add("    :cond_7");
            extraTaintMethods.add("    move-object/from16 v0, v20");
            extraTaintMethods.add("    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;");
            extraTaintMethods.add("    move-object/from16 v4, v18");
            extraTaintMethods.add("    move-object/from16 v3, v19");
            extraTaintMethods.add("    invoke-virtual {v1, v4, v3}, Ljava/lang/String;->replace(Ljava/lang/CharSequence;Ljava/lang/CharSequence;)Ljava/lang/String;");
            extraTaintMethods.add("    move-result-object v1");
            extraTaintMethods.add("    invoke-virtual {v2, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;");
            extraTaintMethods.add("    move-object/from16 v1, v17");
            extraTaintMethods.add("    invoke-virtual {v2, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;");
            extraTaintMethods.add("    :goto_2");
            extraTaintMethods.add("    add-int/lit8 v7, v7, 0x1");
            extraTaintMethods.add("    move-object v5, v3");
            extraTaintMethods.add("    move-object/from16 v1, v26");
            extraTaintMethods.add("    move-object v3, v0");
            extraTaintMethods.add("    move-object/from16 v0, v16");
            extraTaintMethods.add("    goto/16 :goto_0");
            extraTaintMethods.add("    :cond_8");
            extraTaintMethods.add("    move-object/from16 v28, v18");
            extraTaintMethods.add("    move-object/from16 v27, v19");
            extraTaintMethods.add("    move-object/from16 v29, v20");
            extraTaintMethods.add("    move-object/from16 v1, v22");
            extraTaintMethods.add("    move-object/from16 v6, v23");
            extraTaintMethods.add("    move-object/from16 v7, v24");
            extraTaintMethods.add("    move-object/from16 v18, v17");
            extraTaintMethods.add("    invoke-virtual/range {p0 .. p0}, Ljava/lang/reflect/Method;->getReturnType()Ljava/lang/Class;");
            extraTaintMethods.add("    move-result-object v17");
            extraTaintMethods.add("    invoke-virtual/range {v17 .. v17}, Ljava/lang/Class;->getName()Ljava/lang/String;");
            extraTaintMethods.add("    move-result-object v1");
            extraTaintMethods.add("    const-string v6, \")\"");
            extraTaintMethods.add("    invoke-virtual {v2, v6}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;");
            extraTaintMethods.add("    invoke-virtual {v1, v13}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z");
            extraTaintMethods.add("    move-result v6");
            extraTaintMethods.add("    if-eqz v6, :cond_9");
            extraTaintMethods.add("    invoke-virtual {v2, v11}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;");
            extraTaintMethods.add("    goto/16 :goto_3");
            extraTaintMethods.add("    :cond_9");
            extraTaintMethods.add("    invoke-virtual {v1, v10}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z");
            extraTaintMethods.add("    move-result v6");
            extraTaintMethods.add("    if-eqz v6, :cond_a");
            extraTaintMethods.add("    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;");
            extraTaintMethods.add("    goto :goto_3");
            extraTaintMethods.add("    :cond_a");
            extraTaintMethods.add("    invoke-virtual {v1, v8}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z");
            extraTaintMethods.add("    move-result v3");
            extraTaintMethods.add("    if-eqz v3, :cond_b");
            extraTaintMethods.add("    invoke-virtual {v2, v4}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;");
            extraTaintMethods.add("    goto :goto_3");
            extraTaintMethods.add("    :cond_b");
            extraTaintMethods.add("    invoke-virtual {v1, v5}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z");
            extraTaintMethods.add("    move-result v3");
            extraTaintMethods.add("    if-eqz v3, :cond_c");
            extraTaintMethods.add("    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;");
            extraTaintMethods.add("    goto :goto_3");
            extraTaintMethods.add("    :cond_c");
            extraTaintMethods.add("    invoke-virtual {v1, v9}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z");
            extraTaintMethods.add("    move-result v0");
            extraTaintMethods.add("    if-eqz v0, :cond_d");
            extraTaintMethods.add("    invoke-virtual {v2, v14}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;");
            extraTaintMethods.add("    goto :goto_3");
            extraTaintMethods.add("    :cond_d");
            extraTaintMethods.add("    invoke-virtual {v1, v15}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z");
            extraTaintMethods.add("    move-result v0");
            extraTaintMethods.add("    if-eqz v0, :cond_e");
            extraTaintMethods.add("    invoke-virtual {v2, v12}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;");
            extraTaintMethods.add("    goto :goto_3");
            extraTaintMethods.add("    :cond_e");
            extraTaintMethods.add("    invoke-virtual {v1, v7}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z");
            extraTaintMethods.add("    move-result v0");
            extraTaintMethods.add("    if-eqz v0, :cond_f");
            extraTaintMethods.add("    move-object/from16 v0, v23");
            extraTaintMethods.add("    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;");
            extraTaintMethods.add("    goto :goto_3");
            extraTaintMethods.add("    :cond_f");
            extraTaintMethods.add("    move-object/from16 v0, v22");
            extraTaintMethods.add("    invoke-virtual {v1, v0}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z");
            extraTaintMethods.add("    move-result v0");
            extraTaintMethods.add("    if-eqz v0, :cond_10");
            extraTaintMethods.add("    move-object/from16 v0, v21");
            extraTaintMethods.add("    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;");
            extraTaintMethods.add("    goto :goto_3");
            extraTaintMethods.add("    :cond_10");
            extraTaintMethods.add("    move-object/from16 v0, v29");
            extraTaintMethods.add("    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;");
            extraTaintMethods.add("    move-object/from16 v0, v27");
            extraTaintMethods.add("    move-object/from16 v3, v28");
            extraTaintMethods.add("    invoke-virtual {v1, v3, v0}, Ljava/lang/String;->replace(Ljava/lang/CharSequence;Ljava/lang/CharSequence;)Ljava/lang/String;");
            extraTaintMethods.add("    move-result-object v0");
            extraTaintMethods.add("    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;");
            extraTaintMethods.add("    move-object/from16 v0, v18");
            extraTaintMethods.add("    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;");
            extraTaintMethods.add("    :goto_3");
            extraTaintMethods.add("    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;");
            extraTaintMethods.add("    move-result-object v0");
            extraTaintMethods.add("    invoke-interface/range {v16 .. v16}, Ljava/util/List;->iterator()Ljava/util/Iterator;");
            extraTaintMethods.add("    move-result-object v1");
            extraTaintMethods.add("    :cond_11");
            extraTaintMethods.add("    :goto_4");
            extraTaintMethods.add("    invoke-interface {v1}, Ljava/util/Iterator;->hasNext()Z");
            extraTaintMethods.add("    move-result v2");
            extraTaintMethods.add("    if-eqz v2, :cond_12");
            extraTaintMethods.add("    invoke-interface {v1}, Ljava/util/Iterator;->next()Ljava/lang/Object;");
            extraTaintMethods.add("    move-result-object v2");
            extraTaintMethods.add("    check-cast v2, Ljava/lang/String;");
            extraTaintMethods.add("    invoke-virtual {v0, v2}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z");
            extraTaintMethods.add("    move-result v2");
            extraTaintMethods.add("    if-eqz v2, :cond_11");
            if (tool instanceof ViaLinTool) {
                extraTaintMethods.add("    invoke-static {v0}, Ljava/lang/PathTaint;->printSourceFound(Ljava/lang/String;)V");
                extraTaintMethods.add("    " + tool.getMoveTaint() + "/from16 v5, p1");
                extraTaintMethods.add("    move-object/from16 v6, p2");
                extraTaintMethods.add("    const v7, " + lineNumber);
                extraTaintMethods.add("    invoke-static {v5, v6, v7}, Ljava/lang/PathTaint;->addTaintSource(Ljava/lang/PathTaint;Ljava/lang/String;I)Ljava/lang/PathTaint;");
                extraTaintMethods.add("    " + tool.getMoveResultTaint() + " p1");
            } else { // TaintDroid
                extraTaintMethods.add("    add-int/lit8 v30, v30, 1");
                extraTaintMethods.add("    or-int p1, p1, v30");
            }
            extraTaintMethods.add("    goto :goto_4");
            extraTaintMethods.add("    :cond_12");
            extraTaintMethods.add("    const-string v1, \"Landroid/content/Intent;->putExtra(Ljava/lang/String;Ljava/lang/String;)Landroid/content/Intent;\"");
            extraTaintMethods.add("    invoke-virtual {v0, v1}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z");
            extraTaintMethods.add("    move-result v0");
            extraTaintMethods.add("    if-eqz v0, :cond_13");
            extraTaintMethods.add("    " + tool.getMoveTaint() + "/from16 v0, p1");
            extraTaintMethods.add("    move-object/from16 v1, p3");
            extraTaintMethods.add("    instance-of v2, v1, Landroid/content/Intent;");
            extraTaintMethods.add("    if-eqz v2, :cond_13");
            extraTaintMethods.add("    invoke-static {v1, v0}, " + tool.addParcelTaint());
            extraTaintMethods.add("    :cond_13");
            extraTaintMethods.add("    " + tool.returnInstr() + " p1");

            extraTaintMethods.add(".end method");
        }
        linesToAdd.add("    " + tool.getMoveResultTaint() + " " + paramRegister);

        return (taintTempReg+3 > maxRegs)? taintTempReg+3 : maxRegs;
    }
}


